### ISSUE TITLE
Internationalization support

### ISSUE THREAD

**Issue by airone01** [Raicuparta/outerwildsmods.com#76]
Hi, I'm a French junior dev.

I think it would be amazing to have internationalization support on the website. I can provide the PR for it (probably using [svelte-i18n](https://github.com/kaisermann/svelte-i18n)) and the french translations myself. Just making an Issue so you guys can tell me if you're not interested/if it might be too much work.
There's also the question of translating the mods descriptions which means adding different descriptions in the DB depending on the language, etc.

Hit me up on what you think about it !

**Comment by Bwc9876** [comment]
Go for it! I think we're gonna keep mod descriptions untranslated for now, but we can see later if/how we wanna do that.

Btw, we have a [discord server](https://discord.gg/eSNbjwBF) if you want to join that so it's easier to talk abt this.

**Comment by Raicuparta** [comment]
I'm gonna say we will almost definitely not want to translate mod descriptions and readmes because those are controlled by each modder and it would be difficult to deal with.

For i18n on the website, one problem is that this is a fully static page, so we can't detect the language on the server before sending the page to the client. Which means users always have to manually pick their preferred language. Which might be fine but I just thought I'd mention it.

But yeah if you open a nice PR we can give it a shot :)
